# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin

admin.autodiscover()
urlpatterns = patterns('',
(r'^dcsmsserver/', include('dcsmsserver.svc.urls')),
(r'^admin/',include(admin.site.urls)),
(r'^$/svc', RedirectView.as_view(url='/index')),
(r'^$/dcsmsserver', RedirectView.as_view(url='/svc/index')),
(r'^$', RedirectView.as_view(url='dcsmsserver/svc/index')) # Just for ease of use.
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

"""
Original - Generated by django
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SiteViz.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)
"""
